### ISSUE TITLE
Two DocumenterTest failures

### ISSUE THREAD

**Issue by Nava2** [umple/umple#114]
Originally reported on Google Code with ID 214

---

**What steps will reproduce the problem?**
1. Run all DocumenterTests on Windows (found on Windows 7)

**What is the expected output? What do you see instead?**

Here's the entire trace for the first failure:

org.junit.ComparisonFailure: Failed at:44 expected:<[<p class="description"><a href="http://try.umple.org?text=here%20is%20an%20example%20to%20consider">Load
the above code into UmpleOnline</a></p>]> but was:<[]>
    at org.junit.Assert.assertEquals(Assert.java:123)
    at cruise.umple.util.SampleFileWriter.assertFileContent(SampleFileWriter.java:106)
    at cruise.umple.docs.DocumenterTest.htmlBodyOne(DocumenterTest.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:73)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:46)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
    at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

Here's the trace for the second:
org.junit.ComparisonFailure: Failed at:44 expected:<[<p class="description"><a href="http://try.umple.org?text=one%20example%20to%20consider">Load
the above code into UmpleOnline</a></p>]> but was:<[]>
    at org.junit.Assert.assertEquals(Assert.java:123)
    at cruise.umple.util.SampleFileWriter.assertFileContent(SampleFileWriter.java:106)
    at cruise.umple.docs.DocumenterTest.htmlMultipleExamples(DocumenterTest.java:77)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:73)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:46)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
    at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

The tests in question are htmlBodyOne and htmlMultipleExamples, and the failure appears
to be exactly the same in both cases (the traces seem identical). Fixing one might
fix the other.

This is with revision 682.

---

Reported by @JoelHobson on 2011-09-15 01:23:20

**Comment by Nava2** [comment]
Did you do a svn up since yesterday. I submitted a patch this morning that should have
fixed this problem, as I too encountered it.

The weird thing is that I thought I had fixed it several days ago too. Then it reappeared.

So please update svn then let me know if the problem goes away. I am no longer getting
this failure locally, nor is the build server getting it.

---

Reported by @umple on 2011-09-15 02:07:40

**Comment by Nava2** [comment]
Reported by @umple on 2012-02-14 22:12:46
- **Status changed**: `Verified`
