### ISSUE TITLE
Infinite recursion in propagateImmutabilityToAllRelationships

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1152]
The code below results in an infinite recursion and hence a crash with the following stack trace. There needs to be logic to prevent this. It could be simply a recursion limit counter set to some moderately low number such as 25 that counts down.

The stack trace:
``` 
java.lang.StackOverflowError
	at cruise.umple.compiler.UmpleClass.notifySubclassesAncestorImmutable(Umple_Code.ump:1901)
	at cruise.umple.compiler.UmpleClass.propagateImmutabilityToAllRelationships(UmpleClass.java:3235)
	at cruise.umple.compiler.UmpleClass.setAncestorIsImmutable(UmpleClass.java:3266)
	at cruise.umple.compiler.UmpleClass.notifySubclassesAncestorImmutable(UmpleClass.java:3244)
	at cruise.umple.compiler.UmpleClass.propagateImmutabilityToAllRelationships(UmpleClass.java:3235)
	at cruise.umple.compiler.UmpleClass.setAncestorIsImmutable(UmpleClass.java:3266)
	at cruise.umple.compiler.UmpleClass.notifySubclassesAncestorImmutable(UmpleClass.java:3244)
```

The code is:

```

class LabManager {
class User {
  String name;
  unique int ID;
  String password;
}

class Director {
  isA User;
  

  1..* -> 1 Inventory;
  1..* -- * Staff;
  1..* -- 1 FundingAccount;
}

class Staff {
  isA User;
  
}

class StaffRole {
  1 <- 1 Staff;
}

class ResearchAssistant {

  isA StaffRole;
}

class ResearchAssociate {

  isA StaffRole;
}

class ProgressDiary {
  1 -- 1 Staff;
}

class WeeklyReport {
  *  <- 1 ProgressDiary;
  Date startDate;
  Date endDate;
  String content;
}

class Product {
  String name;
  unique int productNb;
  int quantity;
  double costPerUnit;
  
  * <- 1 Inventory;
}

class Equipment {
  isA Product;
}

class Supply {
  isA Product;
}

class Inventory {
  singleton;
}

class FundingAccount {
  1 -> * Expense;
}

class Expense {
  Date date;
  double cost;
  ExpenseType type;
  String description;
 enum ExpenseType {EQUIPMENT = 0, SUPPLY = 1, STAFF = 2, TRAVEL = 3} 
}
}

```

**Comment by TimLethbridge** [comment]
Here is another case:

```
class URLMS
{
  class Staff
{
  Role role;
  }

class WeeklyProgressUpdate
{
}

class FundingAccount
{
  * -- * Report report;
  * -- * LabExpense labExpense;
}

class Report
{
}

class LabExpense
{
}

enum Role 
{
  researchAssociate, researchAssistant
}

class Equipment
{
  int quantity;
    class Equipment
  {
  String type;
  }

  class Supply
  {
  String type;
  }
}

}
```

**Comment by TimLethbridge** [comment]
A PR #1180 was attempted, but it was not accepted

**Comment by TimLethbridge** [comment]
Here's a boiled down case that generates the problem:

```
class URLMS
{
  class Staff
  {
    Role role;
  }

  class Equipment
  {
    class Equipment
    {
      String type;
    }
  }
}
```
Note that this is just like saying an Equipment isA Equipment.

Also note that this problem is very similar to issue #1159

**Comment by baala108** [comment]
I understand that and the patch I applied makes sure that the code compiles and produces the expected output.
