### ISSUE TITLE
Crash  when boolean attribute and method clash

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1191]
The following code results in a crash

```
class UserInfo {     
     boolean isAdmin;
     public boolean getIsAdmin(){}
}
```

The stack trace is

```
Exception java.lang.NullPointerException in
 at cruise.umple.compiler.UmpleInternalParser.analyzeMethod(UmpleInternalParser.java:4453)
   => UmpleInternalParser_CodeClass.ump:2818
 at cruise.umple.compiler.UmpleInternalParser.analyzeClassToken(UmpleInternalParser.java:1909)
   => UmpleInternalParser_CodeClass.ump:257
 at cruise.umple.compiler.UmpleInternalParser.analyzeToken(UmpleInternalParser.java:1229)
   => UmpleInternalParser_Code.ump:253
 at cruise.umple.compiler.UmpleInternalParser.analyzeAllTokens(UmpleInternalParser.java:1192)
   => UmpleInternalParser_Code.ump:222
 at cruise.umple.compiler.UmpleInternalParser.analyzeClass(UmpleInternalParser.java:2813)
   => UmpleInternalParser_CodeClass.ump:1150
 at cruise.umple.compiler.UmpleInternalParser.analyzeClassToken(UmpleInternalParser.java:1765)
   => UmpleInternalParser_CodeClass.ump:114
 at cruise.umple.compiler.UmpleInternalParser.analyzeToken(UmpleInternalParser.java:1211)
   => UmpleInternalParser_Code.ump:238
 at cruise.umple.compiler.UmpleInternalParser.analyzeAllTokens(UmpleInternalParser.java:1165)
   => UmpleInternalParser_Code.ump:198
 at cruise.umple.compiler.UmpleInternalParser.analyze(UmpleInternalParser.java:1066)
   => UmpleInternalParser_Code.ump:105
 at cruise.umple.compiler.UmpleModel.run(UmpleModel.java:1463)
   => Umple_Code.ump:250
 at cruise.umple.UmpleConsoleMain.runConsole(UmpleConsoleMain.java:143)
   => Main_Code.ump:178
 at cruise.umple.UmpleConsoleMain.main(UmpleConsoleMain.java:204)
   => Main_Code.ump:237

```

**Comment by hugessen** [comment]
The line that breaks in this scenario is:
[https://github.com/umple/umple/blob/c5fd40a1f818deebd8d84a0c3f6a9fabe32e2a61/cruise.umple/src/UmpleInternalParser_CodeClass.ump#L2817](url)

This case is trying to throw error code `49`, when it should be trying to return error code `1009`. #1007 introduced some code to automatically generate getters and setters for any variables declared. When `public boolean getIsAdmin(){}` in the Umple is interpreted, it conflicts with the auto-generated getter and throws a `49`. In this case, a `1009` error would be more accurate, as it indicates a 

> name conflict with auto-generated getter/setter methods

However, if we reverse the order to
```
class UserInfo {     
     public boolean getIsAdmin(){}
     boolean isAdmin;
}
```
The order of compilation is reversed and _no error is thrown at all_. Both this case and the first case should throw a 1009 error, but neither does, each for different reasons.

**Comment by TimLethbridge** [comment]
PR #1007 for    Issue #962 introduced the notion of having the generated API methods present in the model. There should be error 1009 reported when somebody writes code manually that clashes with generated API

So getIsAdmin() in this example results from that and message 1009 should be generated. PR #1007 hence has some bugs It also seems that the order (whether dup of generated method or the attribute come first) also makes a difference.
