### ISSUE TITLE
Crash on attempt to create multiple inheritance in Shape example

### ISSUE THREAD

**Issue by TimLethbridge** [umple/umple#1220]
The code below crashes with the following trace:

```
Error on line 0 : Compiler Error (Analysis). Could not analyze Umple model. Please report an issue with this entire message and your input code to Umple developers. Stack Trace Follows. To locate the error in the Umple source, set GeneratedSourcePath to root directory where the generated Java is located: e.g. setenv GeneratedSourcePath ~/umple/cruise.umple/src-gen-umple/ Exception java.lang.IndexOutOfBoundsException in at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) at java.base/java.util.Objects.checkIndex(Objects.java:372) at java.base/java.util.ArrayList.get(ArrayList.java:440) at cruise.umple.compiler.UmpleInternalParser.addExtendsTo(UmpleInternalParser.java:14227) at cruise.umple.compiler.UmpleInternalParser.analyzeClass(UmpleInternalParser.java:2829) at cruise.umple.compiler.UmpleInternalParser.analyzeClassToken(UmpleInternalParser.java:1809) at cruise.umple.compiler.UmpleInternalParser.analyzeToken(UmpleInternalParser.java:1255) at cruise.umple.compiler.UmpleInternalParser.analyzeAllTokens(UmpleInternalParser.java:1209) at cruise.umple.compiler.UmpleInternalParser.analyze(UmpleInternalParser.java:1100) at cruise.umple.compiler.UmpleModel.run(UmpleModel.java:1488) at cruise.umple.PlaygroundMain.processCommand(PlaygroundMain.java:747) at cruise.umple.PlaygroundMain.handleMessageFromClient(PlaygroundMain.java:459) at cruise.umple.AbstractServer.receiveMessageFromClient(AbstractServer.java:556) at cruise.umple.ConnectionToClient.run(ConnectionToClient.java:335) 
```

```
// 2D Shapes class hierarchy - sample UML class diagram in Umple
// From Book by Lethbridge and Laganiere, McGraw Hill 2004
// Object-Oriented Software Engineering: Practical Software Engineering using UML and Java
// See http://www.lloseng.com

//Namespace for core of the system.
namespace Shapes.core;

class Shape2D {
 center;
}
//Abstract
class EllipticalShape {
 isA Shape2D;
 semiMajorAxis;
}
//Abstract
class Polygon { isA Ellipse;
 isA Shape2D;
}
class Circle {
 isA EllipticalShape;
}
class Ellipse{
 isA EllipticalShape;
}
class SimplePolygon {
 orientation;
 isA Polygon;
}
class ArbitraryPolygon {
 points;
 isA Polygon;
}
class Rectangle {
 isA SimplePolygon;
 height;
 width;
}
class RegularPolygon {
 numPoints;
 radius;
 isA SimplePolygon;
}

```

**Comment by TimLethbridge** [comment]
This should raise error 34. It seems to happen any time one or both parent classes are defined *after* the attempt at multiple inheritance, as in the following. Although it is actually fine to normally define a class after the isA statement. And if you turn one of them into an interface it works OK.

```
class Polygon {
  isA Ellipse;
 isA Shape2D;
}

class Ellipse{
}
class Shape2D {
}
```

**Comment by TimLethbridge** [comment]
This issue was introduced *after* v.1.27.0

Running the image of v.1.27.0 on the code in the last comment results in the isA Ellipse being ignored (which is also a bug, although not as severe)
