### ISSUE TITLE
Umple-generated code for associations doesn't play nice with Hibernate

### ISSUE THREAD

**Issue by Nava2** [umple/umple#150]
Originally reported on Google Code with ID 250

---

I am reporting this as emailed to me by Étienne Dufresne. I had asked him to see if
he can send me code that reproduces the problem.

The problem was first identified when I wrote a test to create orders on an account.
I would always get the following stack trace on the second createOrder:
...
@Test
public void testCreateOrder() {
Account account = accountDAO.getAccountByEmailAddress(testEmail);
Date date = new Date(System.currentTimeMillis());
assertEquals(true, bitexService.createOrder(account.getAccountId(), TransactionEnum.buy,
CurrencyEnum.btc, 30.50f, 2.0f, date));
assertEquals(true, bitexService.createOrder(account.getAccountId(), TransactionEnum.buy,
CurrencyEnum.usd, 50.99f, 1.0f, date));
assertEquals(true, bitexService.createOrder(account.getAccountId(), TransactionEnum.sell,
CurrencyEnum.btc, 10.41f, 2.0f, date));
assertEquals(true, bitexService.createOrder(account.getAccountId(), TransactionEnum.sell,
CurrencyEnum.btc, 60.67f, 1.0f, date));
}
...

Caused by: org.hibernate.LazyInitializationException: illegal access to loading collection
at org.hibernate.collection.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:366)
at org.hibernate.collection.AbstractPersistentCollection.read(AbstractPersistentCollection.java:111)
at org.hibernate.collection.AbstractPersistentCollection.readElementExistence(AbstractPersistentCollection.java:167)
at org.hibernate.collection.PersistentBag.contains(PersistentBag.java:262)
at is.bitcoin.bitex.domain.Account.addOrder(Account.java:159)
at is.bitcoin.bitex.domain.Order.setAccount(Order.java:175)

Here is a snippet from bitexService.createOrder(...):
...
Account account = accountDAO.getAccountById(accountId);
Order order = new Order(null, price, quantity, expiry, 0, false, currency, transactionType,
account);
String orderId = (String) orderDAO.saveOrder(order);
...

A LazyInitializationException usually occurs when you are trying to access a collection
that was lazy loaded outside of the Hibernate sessions. This really did not make sense
with the way we have Hibernate configured in Spring. The hibernate session factory
singleton is injected in the test class and it is not suppose to be closed until the
transaction is completed. The transactionnal behavior we used also ensured that a transaction
would include all the steps required to perform a use case before committing and then
closing.

When Orders are created, the Order constructor is called, it sets its properties and
it invokes the Order.setAccount(account). Order.setAccount(account) then calls account.addOrder(this)
which first verify if the order that was passed in is already in the list. This is
not an issue when we add an order for the fist time since the full list (which is empty)
has been loaded. However, the exception occurs during the second createOrder because
Hibernate was not able to retrieve the list its about to insert into. To be quite honest
I don't fully understand why it's not able to retrieve the list of orders since all
this overhead in the same transaction and session as the rest of the use case code.
All I know is that the overhead to link the account and order objects together is confusing
Hibernate. It is unnecessary as Hibernate knows it has to complete the bidirectional association
because the mapping files tell it to. Therefore, replacing the Umple generated code
with POJOs removed that overhead and allows multiple order creation. Also, as you saw
in today's demo, there are no issues when iterating over the list of order of a
particular account (listing all orders on screen)

---

Reported by @umple on 2011-12-06 00:18:11

**Comment by Nava2** [comment]
Reported by @umple on 2012-06-15 15:27:39
- **Labels added**: Priority-Low, Diffic-Med
- **Labels removed**: Priority-Medium

**Comment by Nava2** [comment]
Reported by @umple on 2012-09-27 20:12:57
- **Owner removed**
- **Labels added**: Priority-VLow
- **Labels removed**: Priority-Low
