### ISSUE TITLE
Certain standalone reflexive associations won't parse and don't give error message

### ISSUE THREAD

**Issue by Nava2** [umple/umple#158]
Originally reported on Google Code with ID 258
Owned by @umple

---

**What steps will reproduce the problem?**

Enter the following code

Case 1:

class Truck{}

association {
- Truck -- \* Truck;
  }

---

Case 2:

association {
- Truck -- \* Truck;
  }
## 

Case 3:

association {
  1 Truck -- \* Truck;
}

All crash the compiler, but in different places.

Case 1 and 2 gives
java.lang.RuntimeException: Unable to create Association, must have 2 ends
at cruise.umple.compiler.Association.<init>(Association.java:39)

Case 3 gives
Exception in thread "main" java.lang.NullPointerException
    at cruise.umple.compiler.UmpleInternalParser.analyzeAllAssociations(UmpleInternalParser.java:584)

The first case can be fixed by chaining multiplicity to 0..1; the other cases can be
fixed by doing that and also defining a the missing class.

---

Reported by @umple on 2012-01-23 18:42:18

**Comment by Nava2** [comment]
Reported by @umple on 2012-02-15 17:46:57
- **Labels added**: Priority-High, Component-SemanticsAndGen
- **Labels removed**: Priority-Medium

**Comment by Nava2** [comment]
Reported by @umple on 2012-06-14 15:28:38
- **Labels added**: Diffic-Med

**Comment by Nava2** [comment]
For the first part of this, it is a special case of issue 195, which is being worked
on.

---

Reported by @umple on 2012-09-21 20:17:32

**Comment by Nava2** [comment]
This bug has been fixed during the fixing of issue 195

---

Reported by @umple on 2012-09-27 22:52:26
- **Status changed**: `Fixed`
