### ISSUE TITLE
Method name of two characters or less fails

### ISSUE THREAD

**Issue by Nava2** [umple/umple#178]
Originally reported on Google Code with ID 278
Owned by @umple

---

**What steps will reproduce the problem?**
Try compiling
class X {

   void m1()
   {
       z=1;
   }
}
**What is the expected output? What do you see instead?**

Should compile but crashes with the stack trace below. Simply making the method name
one character longer solves the problem.
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index
out of range: 3
    at java.lang.String.substring(String.java:1934)
    at cruise.umple.compiler.UmpleInternalParser.verifyIfMethodIsConstructorOrGetSet(UmpleInternalParser.java:922)
    at cruise.umple.compiler.UmpleInternalParser.analyzeMethod(UmpleInternalParser.java:1079)
    at cruise.umple.compiler.UmpleInternalParser.analyzeClassToken(UmpleInternalParser.java:537)
    at cruise.umple.compiler.UmpleInternalParser.analyzeToken(UmpleInternalParser.java:230)
    at cruise.umple.compiler.UmpleInternalParser.analyzeAllTokens(UmpleInternalParser.java:206)
    at cruise.umple.compiler.UmpleInternalParser.analyzeClass(UmpleInternalParser.java:641)
    at cruise.umple.compiler.UmpleInternalParser.analyzeClassToken(UmpleInternalParser.java:460)
    at cruise.umple.compiler.UmpleInternalParser.analyzeToken(UmpleInternalParser.java:220)
    at cruise.umple.compiler.UmpleInternalParser.analyzeAllTokens(UmpleInternalParser.java:182)
    at cruise.umple.compiler.UmpleInternalParser.analyze(UmpleInternalParser.java:148)
    at cruise.umple.compiler.UmpleModel.run(UmpleModel.java:636)
    at cruise.umple.UmpleConsoleMain.main(UmpleConsoleMain.java:61)

---

Reported by @umple on 2012-02-14 22:14:52

**Comment by Nava2** [comment]
Reported by @umple on 2012-02-15 17:29:54
- **Labels added**: Component-Metamodel

**Comment by Nava2** [comment]
I will be looking into fixing this.  Based on what I currently see in the code the problem
is literally due to the fact that we have this:

String accessorName = methodName.substring(0, 3).

Problem is obvious, its 2 characters and we're asking for 3.

Researching fix, as its a bit entrenched I believe.

---

Reported by @EmperorJordan on 2012-02-17 00:00:57

**Comment by Nava2** [comment]
I have submitted a fix for this.  Need verification.

---

Reported by @EmperorJordan on 2012-02-17 02:08:05
- **Status changed**: `Fixed`
