### ISSUE TITLE
Undirected 0..1 association to same class causes total failure

### ISSUE THREAD

**Issue by Nava2** [umple/umple#195]
Originally reported on Google Code with ID 295
Owned by @umple

---

**What steps will reproduce the problem?**

Compile the following

class X {
    0..1 -> 0..1 X;
}

**What is the expected output? What do you see instead?**

Causes the compiler to fail with no output

---

Reported by @umple on 2012-05-08 22:05:45

**Comment by Nava2** [comment]
Reported by @umple on 2012-06-14 18:07:05
- **Labels added**: Priority-High, Diffic-Easy, Correctness
- **Labels removed**: Priority-Medium

**Comment by Nava2** [comment]
I am going to use this issue as a tutorial to help people who are new on the Umple project
to learn how to fix bugs. I will document every step of the process of fixing this
bug.

The first thing I did was reproduce the bug in UmpleOnline. Indeed, UmpleOnline said
it could not read the generated code.

So the next thing I did was copy the failing code to a file and compile that file.
The result was the following Java stack trace, indicating that a RuntimeException is
being thrown with message "Unable to create Association, must have 2 ends".

Exception in thread "main" java.lang.RuntimeException: Unable to create Association,
must have 2 ends
    at cruise.umple.compiler.Association.<init>(Association.java:44)
    at cruise.umple.compiler.UmpleInternalParser.createAssociation(UmpleInternalParser.java:1680)
    at cruise.umple.compiler.UmpleInternalParser.analyzeAssociation(UmpleInternalParser.java:1741)
    at cruise.umple.compiler.UmpleInternalParser.analyzeinlineAssociation(UmpleInternalParser.java:1791)
    at cruise.umple.compiler.UmpleInternalParser.analyzeClassToken(UmpleInternalParser.java:762)
    at cruise.umple.compiler.UmpleInternalParser.analyzeToken(UmpleInternalParser.java:382)
    at cruise.umple.compiler.UmpleInternalParser.analyzeAllTokens(UmpleInternalParser.java:358)
    at cruise.umple.compiler.UmpleInternalParser.analyzeClass(UmpleInternalParser.java:920)
    at cruise.umple.compiler.UmpleInternalParser.analyzeClassToken(UmpleInternalParser.java:649)
    at cruise.umple.compiler.UmpleInternalParser.analyzeToken(UmpleInternalParser.java:372)
    at cruise.umple.compiler.UmpleInternalParser.analyzeAllTokens(UmpleInternalParser.java:334)
    at cruise.umple.compiler.UmpleInternalParser.analyze(UmpleInternalParser.java:300)
    at cruise.umple.compiler.UmpleModel.run(UmpleModel.java:661)
    at cruise.umple.UmpleConsoleMain.main(UmpleConsoleMain.java:69)

---

Reported by @umple on 2012-09-21 16:54:57
- **Status changed**: `Started`

**Comment by Nava2** [comment]
Any time an exception is thrown, it is unacceptable. An error message should be produced
instead. However, there are still a few places in the code where exceptions are being
thrown that were added in the very earliest days of the Umple compiler. We need to
track this down and replace it with an error message.

Next I am going to locate the place where this exception is being thrown. It appears
to be in the constructor of Association file Association.java. However, it is critical
to edit the .ump files, not the generated java files. So we have to search for where
this occurs in the .ump files.

---

Reported by @umple on 2012-09-21 16:58:07

**Comment by Nava2** [comment]
A search of the .ump files (using grep or Eclipse or any other pattern matching search
tool) does not uncover the 'Unable to create'. However there are many such phrases
in generated Umple code. A search reveals that this phrase is coming from the generated
Association.java class and so is being generated by Umple. 

A deeper look shows that this is being triggered when there is a violation of association
constraints (i.e. multiplicity). An association must have two ends, and not enough
are being passed to the constructor.

So we look up the call hierarchy for UmpleInternalParser.createAssociation(UmpleInternalParser.java:1680
We have to locate this in the .ump files.

---

Reported by @umple on 2012-09-21 17:25:31

**Comment by Nava2** [comment]
Using a search tool we quickly find the createAssociationMethod in UmpleInternamParser_CodeClass.ump
 (as I write this it is at line 1103). We are going to either have to put a try-catch
block around where this constructs an association, or else detect the erroneous input
that is causing the run-time exception and prevent it, or raise an error message.

Before we do that, let us try, however to consider why the generated code is failing.
To do that, we can look at the generated method Association.java.

Line 42 says '    if (!didAddEnds)' and the didAddEnds variable is set by setEnds()

A look at setEnds suggests that the problem might be rejection if the two ends are
the same. That makes sense -- here we are trying to create a reflexive association,
so the two ends are the same. What is happening is that essentially only one end is
being added because the two identical ends are being considered as one.

A look at the user manual: www.umple.org/ReflexiveAssociations.html shows that reflexive
associations must either be symmetrical (using the 'self' keyword) or asymmetrical,
requiring two role names to make the two ends of the association have different names.
The problem code is therefore syntactically insufficient.

In fact, the same error occurs if we type:

class X {
    \* -> \* X;
}

So it doesn't matter that it happened that the multiplicity was 0..1.

The answer then must be to trap this kind of association when it is specified, and
raise an error message that says something like: 'Reflexive associations must have
role names or must use the self keyword if symmetric'. We would then add a user manual
entry explaining that error in more detail.

Our work is therefore laid out for us:
1. Create tests for these cases asserting that they will cause errors. Make sure the
   tests fail.
2. Add an error message to handle the situation.
3. Add a user manual page for the error message to help users get more help.
4. Detect this situation and raise the error message.

Actually, items 1-3 can be done in any order. Item 4 should be done last.

---

Reported by @umple on 2012-09-21 19:58:01

**Comment by Nava2** [comment]
Before we go on, let's see if we can generalize the problem. How about the following
code:

class X {
    1..\* -> \* X;
}

It seems this generates the same result as if we had typed

class X {
    \* self xs;
}

And this case

class X {
    \* -> 1..\* X;
}

Is the same except that the lower bound is now 1

These cases are actually strange because only the second multiplicity is being respected.

So the issue is really that the identical association ends in the original erroneous
code causes failure, but perhaps unnecessarily.

Here's another case:

class X {
    1..\* self;
}

This generates bad code! Aha. Different issue entirely though. Let's raise a separate
issue. 
Actually, on examination, it is a special case of issue 229, which I updated to reflect
this new case.

While browsing issues to see if there is a match for this case, I came across issue
158. That issue raises another test case for this issue:

class X()
association (
- X -- \* X;
  }

When we finish with this issue 195, we should go back and report that part of issue
158 has been resolved.

---

Reported by @umple on 2012-09-21 20:29:05

**Comment by Nava2** [comment]
Before proceeding, one more thought: The error message we want to raise should likely
go in UmpleInternalParser_Code.ump at line 1164. We are going to call setFailedPosition
with the new error message, when we want users to specify the reflexive syntax.

---

Reported by @umple on 2012-09-21 20:32:37

**Comment by Nava2** [comment]
In order to add the test cases, we are going to be first adding the .ump code that has
errors to the directory
cruise.umple/test/cruise/umple/compiler

Examination of this directory shows that the .ump files used for testing are organized
with three-digit numbers preceding them into groups. A search shows that tests for
reflexive associations have prefix 009. We will therefore add several such files.

The file UmpleParserTest.java contains the actual tests. We are going to add some 'assertFailedParse'
tests with the new error message.

---

Reported by @umple on 2012-09-21 20:52:49

**Comment by Nava2** [comment]
First we wil add the error message and the documentation for the proposed error. We
are going to need this in the tests. We are going to practice agile development by
making extremely small commits.

Before doing any changes, I did 'svn update' to make sure I had the latest code. I
also ran a full build
ant -Dmyenv=local
to make sure my respository is in good shape.

To add an error message, I modifed the file en.error (in cruise.umple/src). 
Error messages are organized one per line, with an error number, a colon, a severity
1= severe error, 2=error, 3=minor error, 4=error in base language (warning in Umple),
5=warning.
The URL is the URL in the manual page we will create, then comes the message, with
parameters to be substituted, starting with {0}

Error message numbers are grouped to keep certain types of errors together. The easiest
way to create a new message is to duplicate an old one and edit it.

 I added error message 21 (see the file to see the message). I called it a level 3
error. We could choose to find a way to generate valid code for these cases, but we
do not do so.

I am not going to commit yet because I want to add the user manual page, so that when
this error is displayed,  
there is some help available to solve the problem.

User manual page specifications are found in build/reference. And error message pages
are in the 9000 series. I am going to create user manual page 9021 (where 21 is the
error message number). I do this by duplicating 
page spec 9020 to create page 9021.

When the page is created I run a full build as before. I find no change to the system
and no test cases passing or failing. I also ensure the documenter runs to generate
the actual manual page by running
ant -Dmyenv=local -f build.umple.xml packageDocs

---

Reported by @umple on 2012-09-25 19:43:06

**Comment by Nava2** [comment]
Upon completion, we see the error message page in
umple/dist/cruise.umple/reference/E021InvalidReflexiveAssociation.html
It is important to actually open the page and test its links.

Next I am going to commit my changes. I just changed two files. The first thing I do,
and this is _critical_ is to do svn add on the new manual page spec file I created,
otherwise it won't get into the system. Then I do the commit. You can see the results
of revision 2037 at this URL:
http://code.google.com/p/umple/source/detail?r=2037
I also go to http://cc.umple.org and verify that the build worked for this in the system.
The result is build 3285, with results that can be seen at:
http://cruise.eecs.uottawa.ca:8080/dashboard/tab/build/detail/Umple/20120925154926

If you are not a committer, you can't directly commit, you send a patch to a committer.
Instructions are here: http://code.google.com/p/umple/wiki/CreatingAndApplyingPatches

Note that the manual still needs 'deploying' on the server. Only an administrator can
do that. We will leave that for now.

---

Reported by @umple on 2012-09-25 19:59:10

**Comment by Nava2** [comment]
Next I am going to add some test cases.

First in cruise.umple/test/cruise/umple/compiler I add 16 .ump files that contain code
to cover many different cases. Some cases should generate new error 21, and some cases
should not. Some cases are for 0..1, while others are for \* multiplicity. Some are
for directed associations, and others or not. We can't test exhaustively, but the following
16 files were added as revision 2039.

Note that we haven't actually created the junit tests yet. Adding the test data first
is a way to be agile, and to commit in baby steps.

009_ReflexiveDirectedManyError21.ump
009_ReflexiveDirectedManyRightRole.ump
009_ReflexiveDirectedZeroOneError21.ump
009_ReflexiveDirectedZeroOneReverseError21.ump
009_ReflexiveDirectedZeroOneRightRole.ump
009_ReflexiveDirectedZeroOneSeparateAssocError21.ump
009_ReflexiveDirectedZeroOneSeparateAssocRightRole.ump
009_ReflexiveNonDirectedManyError21.ump
009_ReflexiveNonDirectedManyRightRole.ump
009_ReflexiveNonDirectedManySeparateAssocError21.ump
009_ReflexiveNonDirectedManySymmetricRightRole.ump
009_ReflexiveNonDirectedZeroOneError21.ump
009_ReflexiveNonDirectedZeroOneRightRole.ump
009_ReflexiveNonDirectedZeroOneSeparateAssocError21.ump
009_ReflexiveNonDirectedZeroOneSeparateAssocRightRole.ump
009_ReflexiveNonDirectedZeroOneSymmetricRightRole.ump

---

Reported by @umple on 2012-09-25 20:55:01

**Comment by Nava2** [comment]
To create the tests, I added three tests called reflexiveCasesNoError21() for the cases
I expect to _not_ trigger error 21, but which are similar to the error 21 cases, reflexiveAndError21CasesDirected()
for the error cases involving directed associations, and reflexiveAndError21CasesNonDirected()
for the remained. These are in file UmpleParserTest.java. The tests will assert whether
each of the above files does or does not create the error.

I then do a build and expect to see errors where I am expecting error 21. Of course
I do not yet commit the new tests as is because that would break the build, so after
checking that the expected failures occur, I will add @Ignore after the new test and
commit the test. This allows me to switch the test off for everybody else while I continue
to work. After committing, I remove the ignore line.'

To do the build I run 
ant -Dmyenv=local -f build.umple.xml umpleSelf compile template.test

Running the build gives me 
    [junit] TEST cruise.umple.builder.BuilderTest FAILED
    [junit] TEST cruise.umple.compiler.UmpleInternalParserTest FAILED
    [junit] TEST cruise.umple.compiler.UmpleParserTest FAILED
    [junit] TEST cruise.umple.compiler.UmpleXtextParserTest FAILED

Don't be fooled by the fact that it also says BUILD SUCCESSFUL

I open up the QA landing page at qa/cruise.umple/index.html to see the results

I see 'Unable to create Association, must have 2 ends', which is the error we are setting
out to fix. This occur in both of the tests.

Next I add the @ignore in the failing cases and run again.

Success! We are now ready to actually build the code. I am going to commit the tests
with the ignore, so that little piece of work is done. This is revision 2041 and build
3288.

---

Reported by @umple on 2012-09-26 10:58:01

**Comment by Nava2** [comment]
I have solved the problem by adding a few lines of code to the analzeAssociation method
in UmpleInernalParser_CodeClass.ump file. Plus I had to fix a bug in one of the two
places where this method is called, because it wasn't expecting a null return.

All the test cases now pass (I removed the @ignore). Incidentally, while working on
it, I pasted the test case code all into UmpleOnline to speed the process of detecting
errors. As the errors went away, I deleted the relevant bits of code until I had just
passing code left.

While doing this I did also add two debug messages to en.error. Message 8005 in particular
is useful to emit debug info as a warning while debugging code you are writing.

The commit to fix the error is revision 2045

---

Reported by @umple on 2012-09-27 21:20:46
- **Status changed**: `Fixed`

**Comment by Nava2** [comment]
One thing I forgot to mention: In an earlier comment I discussed error messages. Actually
severity 1 and 2 are errors. Parsing should stop. Severity 3 and 4 are warnings. Multiple
warnings can be generated. Severity 5 is reserved for messages generated after compilation,
such as when compiling the resulting Java code.

---

Reported by @umple on 2012-09-28 10:43:37
