### ISSUE TITLE
Crash when there are two reflexive associations, and a symmetric comes before an asymmetric

### ISSUE THREAD

**Issue by Nava2** [umple/umple#237]
Originally reported on Google Code with ID 338
Owned by @vahdat-ab

---

**What steps will reproduce the problem?**

Enter

class Course {
- self isMutuallyExclusiveWith;
  - successor -- \* Course prerequisite;
    }

Result:

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.rangeCheck(ArrayList.java:604)
    at java.util.ArrayList.get(ArrayList.java:382)
    at cruise.umple.compiler.UmpleClass.getAssociation(UmpleClass.java:130)
    at cruise.umple.compiler.UmpleInternalParser.addUnlinkedAssociationVariables(UmpleInternalParser.java:1155)
    at cruise.umple.compiler.UmpleInternalParser.postTokenClassAnalysis(UmpleInternalParser.java:821)
    at cruise.umple.compiler.UmpleInternalParser.postTokenAnalysis(UmpleInternalParser.java:404)
    at cruise.umple.compiler.UmpleInternalParser.analyze(UmpleInternalParser.java:301)
    at cruise.umple.compiler.UmpleModel.run(UmpleModel.java:661)
    at cruise.umple.UmpleConsoleMain.main(UmpleConsoleMain.java:69)

But if you reverse the order of the associations, then it is fine.

---

Reported by @umple on 2012-09-28 14:41:11

**Comment by Nava2** [comment]
The fix needs to be made in addUnlinkedAssociatioVariables in UmpleInternalParser_CodeClass.ump,
around line 577. The existing code assumes that given the 'AssociationVariables' in
a class map exactly to the assciation variables. Because they don't there is an index
out of bounds error.

---

Reported by @umple on 2012-09-28 18:31:38

**Comment by Nava2** [comment]
Reported by @umple on 2013-04-30 13:45:43
- **Owner removed**

**Comment by Nava2** [comment]
Reported by @umple on 2013-05-01 01:59:05
- **Owner changed**: @vahdat-ab

**Comment by Nava2** [comment]
Reported by @umple on 2013-05-17 21:32:54
- **Status changed**: `Verified`
