### ISSUE TITLE
ToString null pointer exception and failure to point to correct .ump line

### ISSUE THREAD

**Issue by Nava2** [umple/umple#286]
Originally reported on Google Code with ID 387
Owned by `redeyedmars`

---

In the following code there are multiple errors

Firstly, the error is at X.main line 8 not 6.

Second B.Java:124 - the ToString method is creating a Null Pointer Exception, which
it should not.

java.lang.NullPointerException
    at B.toString(B.java:124)
    at java.lang.String.valueOf(String.java:2854)
    at java.io.PrintStream.println(PrintStream.java:821)
    at X.main(test.ump:6)

class X {
  a;
  0..1 -- \* B;

  public static void main(String[] args) {
    B b;
    b = new B("cat");
    System.out.println(b);
  }
}

class B {
  name;
  sm {
    s1 {
      e1 -> s2;
    }
    s2 {}
  }
}

---

Reported by @umple on 2013-05-18 05:39:18

**Comment by Nava2** [comment]
Reported by `redeyedmars` on 2013-05-31 14:47:52
- **Status changed**: `Fixed`
