### ISSUE TITLE
Infinite recursion in java split call in Generator_SuperCodeGenerator.ump 58

### ISSUE THREAD

**Issue by Nava2** [umple/umple#486]
Originally reported on Google Code with ID 588

---

Infinite recursion occurs when you generate Java from the following

umpleonline/ump/AgentsCommunication.ump

and execute the Java. The result is

```
 [java] java.lang.StackOverflowError
 [java]     at java.util.ArrayList.subListRangeCheck(ArrayList.java:959)
 [java]     at java.util.ArrayList.subList(ArrayList.java:954)
 [java]     at java.lang.String.split(String.java:2311)
 [java]     at java.lang.String.split(String.java:2355)
 [java]     at cruise.umple.compiler.SuperCodeGenerator.translate( Generator_SuperCodeGenerator.ump:58)
```

This is new as of Geoffrey'scommit June 6

---

Reported by @umple on 2014-06-09 18:20:04

**Comment by Nava2** [comment]
Hello, I just tested the generated java code from the AgentsCommunication.ump, and I
am not having the recursion problem. Is this error still happening to you?

---

Reported by @roffs on 2014-07-08 15:41:48

**Comment by Nava2** [comment]
Reported by `redeyedmars` on 2014-07-08 17:10:47
- **Status changed**: `Fixed`
