### ISSUE TITLE
Eclipse hangs when a circular generalization error message is expected

### ISSUE THREAD

**Issue by Nava2** [umple/umple#490]
Originally reported on Google Code with ID 592
Owned by @CraigBryan

---

**What steps will reproduce the problem?**
1. Attempt to compile the following code with the eclipse plugin

class A {
  isA B;
  name;
}

class B {
  isA A;
}

**What is the expected output? What do you see instead?**
The plugin should output a circularity error "Class 'B' cannot cyclically extend Class
'A'"

Instead, eclipse hangs.

Note that the variable underneath the "isA B" is required. Without the variable, the
error is generated properly. The variable can be in either class, but it is required
to reproduce the error.

This error also causes umpleonline to become unresponsive.

---

Reported by @CraigBryan on 2014-06-10 16:56:59

**Comment by Nava2** [comment]
Another situation with this that is possibly related.
The code below, when compiled in eclipse, compiles sometimes, but other times gives
a stackoverflow exception (stacktrace below):

class A {
  isA B;
  isA C;
}

class B {
  isA A;
}

class C {

}

!ENTRY org.eclipse.ui 4 0 2014-06-10 13:25:17.254
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.StackOverflowError
    at java.util.Collections$UnmodifiableList.<init>(Collections.java:1204)
    at java.util.Collections$UnmodifiableRandomAccessList.<init>(Collections.java:1282)
    at java.util.Collections.unmodifiableList(Collections.java:1190)
    at cruise.umple.compiler.UmpleClass.getSubclasses(UmpleClass.java:856)
    at cruise.umple.compiler.UmpleClass.notifySubclassesAncestorImmutable(UmpleClass.java:2443)
    at cruise.umple.compiler.UmpleClass.propagateImmutabilityToAllRelationships(UmpleClass.java:2437)
    at cruise.umple.compiler.UmpleClass.setAncestorIsImmutable(UmpleClass.java:2466)
    at cruise.umple.compiler.UmpleClass.notifySubclassesAncestorImmutable(UmpleClass.java:2445)
    at cruise.umple.compiler.UmpleClass.propagateImmutabilityToAllRelationships(UmpleClass.java:2437)
    at cruise.umple.compiler.UmpleClass.setAncestorIsImmutable(UmpleClass.java:2466)
    at cruise.umple.compiler.UmpleClass.notifySubclassesAncestorImmutable(UmpleClass.java:2445)
    at cruise.umple.compiler.UmpleClass.propagateImmutabilityToAllRelationships(UmpleClass.java:2437)
    at cruise.umple.compiler.UmpleClass.setAncestorIsImmutable(UmpleClass.java:2466)
    at cruise.umple.compiler.UmpleClass.notifySubclassesAncestorImmutable(UmpleClass.java:2445)
    at cruise.umple.compiler.UmpleClass.propagateImmutabilityToAllRelationships(UmpleClass.java:2437)
    at cruise.umple.compiler.UmpleClass.setAncestorIsImmutable(UmpleClass.java:2466)
    at cruise.umple.compiler.UmpleClass.notifySubclassesAncestorImmutable(UmpleClass.java:2445)
    at cruise.umple.compiler.UmpleClass.propagateImmutabilityToAllRelationships(UmpleClass.java:2437)
    at cruise.umple.compiler.UmpleClass.setAncestorIsImmutable(UmpleClass.java:2466)
    at cruise.umple.compiler.UmpleClass.notifySubclassesAncestorImmutable(UmpleClass.java:2445)
    at cruise.umple.compiler.UmpleClass.propagateImmutabilityToAllRelationships(UmpleClass.java:2437)
    at cruise.umple.compiler.UmpleClass.setAncestorIsImmutable(UmpleClass.java:2466)
....etc

---

Reported by @CraigBryan on 2014-06-10 18:32:54

**Comment by Nava2** [comment]
An even simpler case causes this hang:

class A {
  isA A;
  variable;
}

This causes the hang with the latest eclipse plugin, umpleonline, the current version
of umple.jar, and an older version of umple.jar (umple_1.19.0.3287.jar).

---

Reported by @CraigBryan on 2014-06-11 13:46:03
- **Owner changed**: @CraigBryan
- **Status changed**: `Started`
- **Labels added**: Priority-VHigh
- **Labels removed**: Priority-Medium
- **cc removed:** -@umple

**Comment by Nava2** [comment]
Another related problem with interfaces:

This code detects the cycle:

interface A {
  isA A;
  variable;
}

but, the follow code is processed without error:

interface A {
  variable;
  isA A;
}

---

Reported by @CraigBryan on 2014-06-11 14:54:28

**Comment by Nava2** [comment]
This bug appears to be caused by the fix for issue 441.

Specifically, line 1183 of UmpleInternalParser_CodeClass.ump.

---

Reported by @CraigBryan on 2014-06-11 18:35:24

**Comment by Nava2** [comment]
Much of the issue is solved but not the second part of comment 4

---

Reported by @umple on 2014-06-11 20:58:04

**Comment by Nava2** [comment]
The unsolved part of this issue is covered by issue 494.

---

Reported by @CraigBryan on 2014-06-12 16:17:59
- **Status changed**: `Split`
