### ISSUE TITLE
State machine example "Runway" causes Statetable generation to fail.

### ISSUE THREAD

**Issue by Nava2** [umple/umple#580]
Originally reported on Google Code with ID 682
Owned by @CraigBryan

---

**What steps will reproduce the problem?**
1. Go to umpleonline and choose the "Runway" example from the state machine examples.
2. Generate state tables.

The "Couldn't read results from the Umple compiler!" error appears.

I had expected that the entry, exit, or do actions in some of the states were causing
this error, but I couldn't reproduce the problem with any of those three keywords alone.

---

Reported by @CraigBryan on 2015-02-28 15:39:31

**Comment by Nava2** [comment]
The code to find the correct guardString for a transition causes a StackOverflowError
due to endless recursion.

java.lang.StackOverflowError
    at java.util.HashMap.resize(HashMap.java:581)
    at java.util.HashMap.addEntry(HashMap.java:879)
    at java.util.HashMap.put(HashMap.java:505)
    at cruise.umple.compiler.JavaGenerator.initializeLangaugeBasedVariables(JavaGenerator.java:2497)
    at cruise.umple.compiler.SuperCodeGenerator.<init>(SuperCodeGenerator.java:45)
    at cruise.umple.compiler.JavaGenerator.<init>(JavaGenerator.java:36)
    at cruise.umple.compiler.StateTableRow.extractGuardString(Generator_CodeStateTables.ump:227)
    at cruise.umple.compiler.StateTableRow.extractGuardString(StateTableRow.java:421)
    at cruise.umple.compiler.StateTableRow.extractGuardString(StateTableRow.java:421)
    at cruise.umple.compiler.StateTableRow.extractGuardString(StateTableRow.java:421)
    at cruise.umple.compiler.StateTableRow.extractGuardString(StateTableRow.java:421)

---

Reported by @CraigBryan on 2015-03-01 16:41:13

**Comment by Nava2** [comment]
After some trial and error, I believe this occurs when a guarded transition exists in
a sub-sub-state (a doubly nested state). Transitions with guards in more deeply nested
states also have this error.

Here's a simple example:

class A {
  boolean guard;
  sm {
    First{ ev1 -> Second; }
    Second{ a{ b{ ev1[guard] -> First; } } }
  }
}

Interestingly, this code (with only a singly nested state) doesn't cause the error.

class A {
  boolean guard;
  sm {
    First{ ev1 -> Second; }
    Second{ a{ ev1[guard] -> First; } }
  }
}

---

Reported by @CraigBryan on 2015-03-01 16:58:19

**Comment by Nava2** [comment]
This issue was closed by revision r5169.

---

Reported by @CraigBryan on 2015-03-02 14:34:56
- **Status changed**: `Fixed`
