### ISSUE TITLE
Download umple.jar with Ivy on build. Was: Get java -jar umple.jar to run (as it used to) dependency free

### ISSUE THREAD

**Issue by aforward** [umple/umple#614]
(SEE end comments - as this issue is mostly done)

The old build system would create a "fat" umple.jar that contained all dependencies and would be run from anywhere without the need for other jars to be present in certain specific locations.

We want this functionality migrated from the old system (SVN on googlecode) to the new system (hello github).

**Comment by aforward** [comment]
For documentation purposes, here is how you can reproduce the problem

Create the umple-latest.jar, move it to /tmp and create a sample.ump file.

When you try to run it, you will fail.

```
root@6097977f5b12:/tmp# java -jar umple-latest.jar me.ump 
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionException
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
    at java.lang.Class.privateGetMethodRecursive(Class.java:3040)
    at java.lang.Class.getMethod0(Class.java:3010)
    at java.lang.Class.getMethod(Class.java:1776)
    at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by Nava2** [comment]
Only step left is to remove the "manual" download and replace it with unjaring the same files but from Ivy to save a step of bandwidth.
