### ISSUE TITLE
Specifying sub-package Generator class as generator

### ISSUE THREAD

**Issue by bitwizeshift** [umple/umple#679]
Manually specifying the generator from command line as a prefix of a `*Generator.class` that exists in a sub-package of `cruise.umple.compiler` will produce an uncaught runtime exception.

Example:
`java --jar umple.jar -g php.PhpClass <umpfiles...>`

Output:

```
Umple compiler error. Stack trace follows
To locate the error in the original Umple source, set GeneratedSourcePath to where the generated Java is located:
e.g. setenv GeneratedSourcePath ~/umple/cruise.umple/src-gen-umple
Exception java.lang.RuntimeException in
java.lang.RuntimeException: Unable to instantiate php.PhpClass.
    at cruise.umple.compiler.UmpleModel.newGenerator(UmpleModel.java:1210)
    at cruise.umple.compiler.UmpleModel.getAllTranslators(UmpleModel.java:1678)
    at cruise.umple.compiler.UmpleInternalParser.checkDefaultedNameConflict(UmpleInternalParser_Code.ump:129)
    at cruise.umple.compiler.UmpleInternalParser.analyze(UmpleInternalParser.java:1056)
    at cruise.umple.compiler.UmpleModel.run(UmpleModel.java:1176)
    at cruise.umple.UmpleConsoleMain.runConsole(UmpleConsoleMain.java:136)
    at cruise.umple.UmpleConsoleMain.main(UmpleConsoleMain.java:178)
Caused by: java.lang.ClassCastException: cruise.umple.compiler.php.PhpClassGenerator cannot be cast to cruise.umple.compiler.CodeGenerator
    at cruise.umple.compiler.UmpleModel.newGenerator(UmpleModel.java:1200)
    ... 6 more
```

Similar things occur with `cpp.CppClass`, etc.

**Comment by TimLethbridge** [comment]
Well the issue is supposed to be that the generators are not php.phpClass, but rather Php. We don't want people typing the names of convoluted generators.

However, the bigger issue is that any mistyping will result in this stack trace. It should just catch this and say this isn't one of the valid generators.

**Comment by bitwizeshift** [comment]
Normal mistyping of names that don't exist (e.g. `java --jar umple.jar -g blah <umpfiles...>` will result in a message of `Code generator blah not found. Check spelling. Specify --help.`.

The issue isn't that the generator doesn't exist, but rather that the class specified does exist but isn't actually a generator (and thus not castable to the expected type)

**Comment by TimLethbridge** [comment]
It just wasn't clear why anybody would bother typing 'php.phpClass'. 

In any case, my suggestion is to grab the grammar rule and use that to get the valid list of generators.
