### ISSUE TITLE
Umple Template Unmatched Expression Block Unhelpful Error

### ISSUE THREAD

**Issue by Diusrex** [umple/umple#711]
For the example code:

```
class Generate
{
    template <<! <<=  !>>
}
```

The error output is:

```
Umple compiler error. Stack trace follows
To locate the error in the original Umple source, set GeneratedSourcePath to where the generated Java is located:
e.g. setenv GeneratedSourcePath ~/umple/cruise.umple/src-gen-umple
Exception java.lang.StringIndexOutOfBoundsException in
java.lang.StringIndexOutOfBoundsException: String index out of range: -3
        at java.lang.String.substring(String.java:1967)
        at cruise.umple.parser.rules.Terminal.parse(ParsingRules_Code.ump:663)
        at cruise.umple.parser.rules.ChainRule.parse(ChainRule.java:73)
 ...
        at cruise.umple.parser.rules.ChainRule.parse(ChainRule.java:73)
        at cruise.umple.parser.rules.RootRule.parse(RootRule.java:60)
        at cruise.umple.parser.analysis.RuleBasedParser.parse(RuleBasedParser.java:190)
        at cruise.umple.parser.analysis.GrammarAnalyzer.execute(GrammarAnalyzer.java:687)
        at cruise.umple.parser.analysis.RuleBasedParser.parse(RuleBasedParser.java:374)
        at cruise.umple.compiler.UmpleModel.run(UmpleModel.java:1209)
        at cruise.umple.UmpleConsoleMain.runConsole(UmpleConsoleMain.java:109)
        at cruise.umple.UmpleConsoleMain.main(UmpleConsoleMain.java:151)
```

The errors for an unmatched code block or comment block is far more useful, giving warning `1007`. Looks like the expression block is not handled properly.

**Comment by TimLethbridge** [comment]
The issue here is extremely complex. It ought to be solved so that when there is a mismatch the parsing 'gives up' and generates a message (from en.error ideally) that says cannot find terminating escape sequence. That would be the long range goal

Short range goal, would be to put a try catch block that generically deals with any parsing failure like this and puts out a more generic message 'Unable to parse, please check syntax'.
